version: "3.8"
services:
    django: &django
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            args:
                ENV: dev
        command: bash -c "/scripts/django-entrypoint.sh"
        volumes:
            - .:/project
            - static_volume:/app/var/static
        ports:
            - "80:8000"
        env_file:
            - .env
        depends_on:
            - postgres
            - redis

    postgres:
        restart: always
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data/
        env_file:
            - .env
        ports:
            - "5432"

    redis:
        image: redis
        ports:
            - "6379:6379"

volumes:
    postgres-data:
    static_volume:
