version: "3.8"
services:
    django: &django
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            args:
                ENV: dev
        command: bash -c "/scripts/django-entrypoint.sh"
        volumes:
            - .:/project
            - static_volume:/app/var/static
        ports:
            - "80:8000"
        env_file:
            - .env
        depends_on:
            - postgres
            - redis

    postgres:
        restart: always
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data/
        env_file:
            - .env
        ports:
            - "5432:5432"

    redis:
        image: redis
        ports:
            - "6379:6379"

    celery:
        <<: *django
        build:
            context: .
            dockerfile: Dockerfile
            args:
                ENV: dev
        command: bash -c "/scripts/celery-entrypoint.sh"
        ports: [ ]
        depends_on:
            - redis
            - rabbitmq

    rabbitmq:
        image: rabbitmq:3-management-alpine
        environment:
            - RABBITMQ_DEFAULT_VHOST=vhost
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=pass
        ports:
            - "5672:5672"
            - "15672:15672"


volumes:
    postgres-data:
    static_volume:

networks:
    default:
        name: mycar_default
        external:
            true
