# Generated by Django 4.1.7 on 2023-03-05 11:40

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_activity",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 5, 11, 40, 44, 838642, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 5, 11, 40, 44, 838778, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
