# Generated by Django 3.2.9 on 2023-03-22 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisLike",
            fields=[
                (
                    "like_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="posts.like",
                    ),
                ),
            ],
            bases=("posts.like",),
        ),
        migrations.RemoveField(
            model_name="like",
            name="is_active",
        ),
    ]
